# These are supported funding model platform

github: # Replace with your GitHub username
patreon: # Replace with your Patreon username
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your tidelift platform-name/package-name e.g., npm/babel
community: # Replace with your community forum URL
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']